[package]
name = "schablone"
version = "0.1.0"
authors = ["teraku"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
tera = "~1.5"
snafu = "~0.6"
